# Data Cleaning & Preprocessing

## Project Overview
This notebook performs the initial cleaning of the Glassdoor Data Science Jobs dataset.

### Objectives
- Load the raw dataset
- Inspect data quality
- Handle missing values
- Clean salary information
- Create salary-related features
- Save a cleaned dataset for feature engineering

The cleaned dataset generated here will be used in the next notebook.

## Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

## Load Dataset

In [ ]:
df = pd.read_csv("C:/Users/AI/OneDrive/Documents/dsjob_eda/data/data_csv/glassdoor_jobs.csv"
)
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

## Dataset Shape

In [3]:
print(f"Rows : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows : 956
Columns : 15

## Dataset Information

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 956 entries, 0 to 955
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         956 non-null    int64
 1   Job Title          956 non-null    str
 2   Salary Estimate    956 non-null    str
 3   Job Description    956 non-null    str
 4   Rating             956 non-null    float64
 5   Company Name       956 non-null    str
 6   Location           956 non-null    str
 7   Headquarters       956 non-null    str
 8   Size               956 non-null    str
 9   Founded            956 non-null    int64
 10  Type of ownership  956 non-null    str
 11  Industry           956 non-null    str
 12  Sector             956 non-null    str
 13  Revenue            956 non-null    str
 14  Competitors        956 non-null    str
dtypes: float64(1), int64(2), str(12)
memory usage: 3.7 MB

## Check Missing Values

In [5]:
df.isnull().sum()

Unnamed: 0           0
Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
dtype: int64

## Basic Statistics

In [7]:
df.describe()

       Unnamed: 0      Rating      Founded
count  956.000000  956.000000   956.000000
mean   477.500000    3.601255  1774.605649
std    276.117729    1.067619   598.942517
min      0.000000   -1.000000    -1.000000
25%    238.750000    3.300000  1937.000000
50%    477.500000    3.800000  1992.000000
75%    716.250000    4.200000  2008.000000
max    955.000000    5.000000  2019.000000

## Drop Unnecessary Column

In [8]:
df = df.drop(columns="Unnamed: 0")

## Check Duplicate Records

In [9]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 356

If duplicates exist

In [10]:
df = df.drop_duplicates()

## Salary Column
Let's inspect the salary column.

In [11]:
df["Salary Estimate"].sample(10)

471     $61K-$119K (Glassdoor est.)
53                               -1
279                              -1
593                              -1
290     $62K-$114K (Glassdoor est.)
291     $71K-$129K (Glassdoor est.)
50       $20K-$39K (Glassdoor est.)
591     $76K-$145K (Glassdoor est.)
44     $110K-$175K (Glassdoor est.)
582     $61K-$100K (Glassdoor est.)
Name: Salary Estimate, dtype: str

## Remove Invalid Salaries
Glassdoor uses -1 for unavailable salaries.

In [12]:
df = df[df["Salary Estimate"] != "-1"].copy()

## Clean Salary Text

**Before**
```
$53K-$91K (Glassdoor est.)
Employer Provided Salary:$120K-$140K
$40-$60 Per Hour
```

**After**
```
$53K-$91K
Employer Provided Salary:$120K-$140K
$40-$60 Per Hour
```

In [13]:
df["Salary Estimate"] = (
    df["Salary Estimate"]
    .str.split("(")
    .str[0]
    .str.strip()
)

Check

In [14]:
df["Salary Estimate"].sample(15)

251          $75K-$140K
387           $56K-$97K
87           $86K-$141K
646          $69K-$121K
129          $76K-$140K
342           $42K-$74K
228          $54K-$115K
437    $24-$39 Per Hour
482         $125K-$210K
498          $81K-$134K
79          $139K-$220K
892          $81K-$132K
293          $74K-$119K
200         $116K-$185K
533         $124K-$199K
Name: Salary Estimate, dtype: object

## Per Hour Salary

In [15]:
df["Per_Hour"] = (
    df["Salary Estimate"]
    .str.contains("Per Hour", case=False, na=False)
    .astype(int)
)

Check

In [16]:
df["Per_Hour"].value_counts()

Per_Hour
0    457
1     10
Name: count, dtype: int64

## Employer Provided Salary

In [17]:
df["Employer_Provided"] = (
    df["Salary Estimate"]
    .str.contains(
        "Employer Provided Salary",
        case=False,
        na=False
    )
    .astype(int)
)

Check

In [18]:
df["Employer_Provided"].value_counts()

Employer_Provided
0    457
1     10
Name: count, dtype: int64

## Remove Salary Descriptors
Now remove unnecessary text.

In [19]:
df["Salary Estimate"] = (
    df["Salary Estimate"]
    .str.replace(
        "Employer Provided Salary:",
        "",
        case=False,
        regex=False
    )
    .str.replace(
        "Per Hour",
        "",
        case=False,
        regex=False
    )
    .str.replace(
        "$",
        "",
        regex=False
    )
    .str.replace(
        "K",
        "",
        regex=False
    )
    .str.strip()
)

Check

Expected output
```
53-91
120-140
40-60
```

In [20]:
df["Salary Estimate"].sample(15)

299     61-106
23      63-105
239      35-62
36      77-135
21      73-119
20      81-130
206     98-182
91      55-100
17     118-189
744      42-79
654      35-65
243     81-167
117    200-275
60     120-189
347     95-161
Name: Salary Estimate, dtype: object

## Split Salary

In [21]:
salary = (
    df["Salary Estimate"]
    .str.split("-", expand=True)
)

Preview

In [22]:
salary.head()

    0    1
0  53   91
1  63  112
2  80   90
3  56   97
4  86  143

## Minimum Salary

In [23]:
df["Min_Salary"] = (
    salary[0]
    .astype(int)
)

## Maximum Salary

In [24]:
df["Max_Salary"] = (
    salary[1]
    .fillna(salary[0])
    .astype(int)
)

## Average Salary

In [25]:
df["Avg_Salary"] = (
    df["Min_Salary"] +
    df["Max_Salary"]
) / 2

## Validate Salary Columns

In [26]:
df[
    [
        "Salary Estimate",
        "Min_Salary",
        "Max_Salary",
        "Avg_Salary",
        "Per_Hour",
        "Employer_Provided"
    ]
].sample(15)

,Salary Estimate,Min_Salary,Max_Salary,Avg_Salary,Per_Hour,Employer_Provided
437,24-39,24,39,31.5,1,0
5,71-119,71,119,95.0,0,0
450,76-142,76,142,109.0,0,0
590,110-184,110,184,147.0,0,0
20,81-130,81,130,105.5,0,0
826,39-67,39,67,53.0,0,0
102,64-106,64,106,85.0,0,0
648,150-238,150,238,194.0,0,0
28,34-61,34,61,47.5,0,0
506,52-85,52,85,68.5,0,0
61,111-176,111,176,143.5,0,0
207,73-124,73,124,98.5,0,0
892,81-132,81,132,106.5,0,0
143,29-50,29,50,39.5,0,0
230,90-179,90,179,134.5,0,0

## Final Check

In [27]:
df.info()

<class 'pandas.DataFrame'>
Index: 467 entries, 0 to 948
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          467 non-null    str
 1   Salary Estimate    467 non-null    object
 2   Job Description    467 non-null    str
 3   Rating             467 non-null    float64
 4   Company Name       467 non-null    str
 5   Location           467 non-null    str
 6   Headquarters       467 non-null    str
 7   Size               467 non-null    str
 8   Founded            467 non-null    int64
 9   Type of ownership  467 non-null    str
 10  Industry           467 non-null    str
 11  Sector             467 non-null    str
 12  Revenue            467 non-null    str
 13  Competitors        467 non-null    str
 14  Per_Hour           467 non-null    int64
 15  Employer_Provided  467 non-null    int64
 16  Min_Salary         467 non-null    int64
 17  Max_Salary         467 non-null    int64
 18  Avg_Salary         467 non-null    float64
dtypes: float64(2), int64(5), object(1), str(11)
memory usage: 1.9+ MB

Missing Values

In [28]:
df.isnull().sum()

Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
Per_Hour             0
Employer_Provided    0
Min_Salary           0
Max_Salary           0
Avg_Salary           0
dtype: int64

## Save Clean Dataset

In [ ]:
df.to_csv(
    "C:/Users/AI/OneDrive/Documents/dsjob_eda/data/cleaned_jobs.csv",
    index=False
)

## Summary
In this notebook, we:
- Loaded the raw Glassdoor dataset
- Removed unnecessary columns
- Filtered invalid salary records
- Cleaned salary information
- Created salary-related features
- Calculated minimum, maximum, and average salaries
- Saved the cleaned dataset for feature engineering

The next notebook focuses on creating new features from the cleaned data.